[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Completely disable secrets scanning - NEXT_PUBLIC vars are meant to be in client bundle
[build.processing]
  skip_processing = false

[build.processing.secrets]
  enabled = false

[[plugins]]
  package = "@netlify/plugin-nextjs"
